Refactoring/popup with form
AlexanderKhasanov/mesto-project pull request #8
Opened 2023-10-05 19:44 UTC by aniarara

2023-10-05 20:47 UTC, AlexanderKhasanov requested changes

2023-10-05 20:47 UTC, AlexanderKhasanov commented on src/components/popupWithForm.js
> +  open() {
Нет необходимости перезаписывать этот метод. Родительский делает тоже самое

2023-10-05 20:47 UTC, AlexanderKhasanov commented on src/components/popupWithForm.js
> +    // this._form.reset();
Правильно как раз таки использовать этот вариант сброса формы. Все ошибки сбросятся благодаря обработчику событий из класса FormValidator

2023-10-05 20:47 UTC, AlexanderKhasanov commented on src/components/popupWithForm.js
> +    const _inputValues = [];
1. Лучше собирать все в объект(this.inputValues[input.name] = input.value;)
2. _inputValues должен быть полек объекта. Т.е. this._inputValues
3. _inputValues лучше создавать в конструкторе. Т.е. в конструкторе прописать this._inputValues = {}. А в этом методе уже наполнять объект

2023-10-06 18:13 UTC, aniarara commented on src/components/popupWithForm.js
> +  open() {
да, но в метод добавления слушателей добавлен слушатель отправки формы, поэтому я добавила его в метод open класса PopupWithForm, в Popup.open же будет использоваться старый _setEventListeners

2023-10-06 19:23 UTC, merged